### ISSUE TITLE
Broken links to `Environment` and other CRDs

### ISSUE THREAD

**Issue by wtam2018** [redhat-appstudio/book#38]
Please fix broken links to [Environment](https://github.com/redhat-appstudio/book/blob/main/ref/application-environment-api.md) on this doc
https://github.com/redhat-appstudio/book/blob/main/ADR/adr-0008-environment-provisioning.md

**Comment by ralphbean** [comment]
@wtam2018 Ah, those are working in the rendered version of the ADRs at https://redhat-appstudio.github.io/book/ADR/0008-environment-provisioning.html, where they refer to some automatically generated API reference documentation.
